version: "3.7"
services: 
  frontend:
    build: cne-sfia2-brief/frontend
    image: frontend:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  backend:
    build: cne-sfia2-brief/backend
    image: backend:latest
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI}
